### ISSUE TITLE
IDE window can no longer be resized/maximized

### ISSUE THREAD

**Issue by suchipi** [ivansafrin/Polycode#611]
On Windows 8.1, Compiled with VS2010. There is no maximization button, and double-clicking the window titlebar doesn't maximize the window, either. A small triangle is drawn in the bottom-right corner of the window (within the border, as part of the IDE), but the window border cannot be grabbed and resized. Pressing the window button with the left and right arrow keys doesn't snap the window to the sides of the monitor either.

The size of the window (which is now stuck) appears to be based on an earlier size stored in my config from a previous version.

**Comment by fodinabor** [comment]
I'm taking a look, but as it looks like it was broken by: 871d761407ad289d1a1f18a74f249619a869c0fb

**Comment by bsanantonio** [comment]
This proposed change removes window borders and window decorations from my game when I run it.

**Comment by fodinabor** [comment]
I'd really love if you guys (not only you) would automatically provide some more information, like:
OS (In this case only windows makes sense - okay), and here it would also be interesting what configuration you're using - resizable or not, fullscreen or not (yeah you're able to make it full screen and it looks like a simple window without border if it has a too small resolution)

**Comment by bsanantonio** [comment]
Oh, my apologies. I don't know too much about the framework yet, so I'm not able to clarify. For what it's worth, this is happening when running the C++ examples (which my project is comprised largely of). I'm on Windows 8.1.

The fix works great for the IDE. What I ended up doing was building the IDE with your fix, and rebuilding the framework without it.

**Comment by fodinabor** [comment]
Hmm.. okay that's intersting - I don't have any problems.. I'll check some more possibilities later..

**Comment by W3aponiz3d** [comment]
Hey fodinabor,

I was having the same issue as bsanantonio. I believe the reason why the fix removes the border and decorations for some people is due to a change in the behavior of the Window Style WS_OVERLAPPED. It doesn't explicitly state it here https://msdn.microsoft.com/en-us/library/windows/desktop/ms632600(v=vs.85).aspx but after looking at the definition for WS_OVERLAPPED I realized it didn't look like it actually had any WS_BORDER or WS_CAPTION defined. WS_SYSMENU is "supposed" to require WS_CAPTION to function correctly, but I have seen mixed reports on that as well.

In any case, I changed line 276 and 277 of Core/Contents/Source/PolyWinCore.cpp from:

SetWindowLongPtr(hWnd, GWL_STYLE, WS_OVERLAPPED | WS_SYSMENU | WS_VISIBLE);
AdjustWindowRect(&rect, WS_OVERLAPPED | WS_SYSMENU, FALSE);

To:

SetWindowLongPtr(hWnd, GWL_STYLE, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_VISIBLE);
AdjustWindowRect(&rect, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU, FALSE);

And it is working correctly for me now.

**Comment by fodinabor** [comment]
Oh - did you only use the one commit.. yeah I see the problem: I fixed it in a next commit in the PR for it :$
#613 would have fixed it :-) completely

**Comment by W3aponiz3d** [comment]
Oh sweet. Yes I did only use the one commit. Hehe. I was unaware of the merged fixes commits. I actually found your fix via a google search. I am now watching your fork though, so hopefully I can catch more in the future.

Currently my team and I have our copy of polycode set up over on a private repo at bitbucket. I'm not a git guru by any means, but I haven't found a good way to merge changes from a completely separate repo. I have tried adding the repo as a remote to our project, fetching it and then merging the two locally, but for some reason git complained about conflicts that weren't there.

I may end up having to add a separate github repository and add it to the project in order to keep up with you guys and contribute back!
